### ISSUE TITLE
NODE_URL for Spotify callback

### ISSUE THREAD

**Issue by soenkegissel** [lemma-io/vivify#27]
Hello,

I just followed your readme very closely and got stuck just after the login form. I believe spotify is calling the redirect URI added to the developer backend, but this doesn't take me anywhere.
In ApplicationModule.java NODE_URL = "https://vivify-backend.herokuapp.com/"
Do I need to setup a heroku node myself with a web api or simular?

Kindest

**Comment by phantompunk** [comment]
Have you created a new app within the [Spotify Dev Console](https://beta.developer.spotify.com/dashboard/)? You can clone this [Backend Repo](https://github.com/bdpham/vivify_backend) and deploy it to your own heroku node. All you should have to change is the Spotify Client ID and Client Secret. Then you can change the NODE_URL

**Comment by soenkegissel** [comment]
Wonderful - I will close and deploy the backend repo.
I just need the free version of heroku to test it, right?

**Comment by bdpham** [comment]
Correct
